import Header from "@/components/Header"
import ToasterWithTheme from "@/components/ToasterWithTheme"
import AuthProvider from "@/lib/providers/AuthProvider"
import "@/styles/globals.css"
import "@/styles/reset.css"
import type { Metadata } from "next"
import { getServerSession } from "next-auth"
import { ThemeProvider } from "next-themes"
import { MoneygraphyRounded } from "./fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()

  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${MoneygraphyRounded.className} antialiased text-dark dark:text-light`}>
        <AuthProvider session={session}>
          <ThemeProvider>
            <Header />
            {children}
            <ToasterWithTheme />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
