import { authOptions } from "@/auth"
import Footer from "@/components/Footer"
import Header from "@/components/Header"
import ToasterWithTheme from "@/components/ToasterWithTheme"
import AuthProvider from "@/lib/providers/AuthProvider"
import CookieProvider from "@/lib/providers/CookieProvider"
import ReactQueryProvider from "@/lib/providers/ReactQueryProvider"
import "@/styles/globals.css"
import "@/styles/reset.css"
import { parseBoolean } from "@/utils/parseBoolean"
import type { Metadata } from "next"
import { getServerSession } from "next-auth"
import { ThemeProvider } from "next-themes"
import { cookies } from "next/headers"
import { MoneygraphyRounded } from "./fonts"
import { NavigationGuardProvider } from "next-navigation-guard"
import RouterPreventer from "@/components/RouterPreventer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)
  const cookieStore = await cookies()
  const noBlind = parseBoolean(cookieStore.get("noBlind")?.value)

  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${MoneygraphyRounded.className} text-dark antialiased dark:text-light`}>
        <AuthProvider session={session}>
          <ReactQueryProvider>
            <CookieProvider noBlind={noBlind}>
              <NavigationGuardProvider>
                <ThemeProvider>
                  <div id="portal" />
                  <Header />
                  {children}
                  <Footer />
                  <ToasterWithTheme />
                </ThemeProvider>
                <RouterPreventer />
              </NavigationGuardProvider>
            </CookieProvider>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
