import AuthProvider from "@/lib/providers/AuthProvider";
import "@/styles/globals.css";
import "@/styles/reset.css";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { MoneygraphyRounded } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${MoneygraphyRounded.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
