name: "run build"

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      NEXT_PUBLIC_API_ROOT: ${{ secrets.NEXT_PUBLIC_API_ROOT }}
      KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
      KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
      NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY }}
      REVALIDATE_SECRET: ${{ secrets.REVALIDATE_SECRET }}
      DEMO_LOGIN_SECRET: ${{ secrets.DEMO_LOGIN_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Environment for build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build
