name: "run build"

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Environment for build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build
