name: Create Release Draft
on:
  push:
    branches:
      - main

jobs:
  create-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
