name: 'PR Flow'

on:
  pull_request:
    types: [opened, reopened, synchronize] # [opened, reopened, synchronize]

jobs:
  slack-pr-review:
    uses: ./.github/workflows/slack-pr-review.yaml
    with:
      SLACK_CHANNEL: "balance-game-notification"
    secrets: inherit