name: 'PR Flow'

on:
  pull_request:
    types: [opened, reopened] # [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  slack-pr-review:
    uses: ./.github/workflows/slack-pr-review.yaml
    secrets: inherit