name: "PR Test"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      NODE_VERSION: 22.x
    secrets: inherit

  slack-error-notification:
    if: ${{ always() && needs.build.result == 'failure' }}
    needs: [build]

    uses: ./.github/workflows/slack-error-notification.yaml
    secrets: inherit
